### ISSUE TITLE
Folding doesn't work when note is opened twice

### ISSUE THREAD

**Issue by clessg** [xolox/vim-notes#117]
When I open a note, close it, and reopen it, folding no longer works.

First, I run `:Note HelloWorld` then save it. Running `:verbose set foldexpr? foldmethod?` shows:

```vim
foldexpr=xolox#notes#foldexpr()
        Last set from ~/projects/dotfiles/vim/plugged/vim-notes/ftplugin/notes.vim
foldmethod=expr
        Last set from ~/projects/dotfiles/vim/plugged/vim-notes/ftplugin/notes.vim 
```

Then I run `:q`. Then I run `:Note HelloWorld` again. This time running `:verbose set foldexpr? foldmethod?` shows:

```vim
foldexpr=0
foldmethod=manual
```

In this case I commented out my own folding config in my `.vimrc`:

```vim
" set foldmethod=indent
" set foldnestmax=3
" set nofoldenable
```

Uncommenting it and trying the above again makes the `foldmethod` `indent` on the second try.

My vim-notes config is just:

```vim
let g:notes_directories  = ['~/vim-notes']
```

Am I the only one experiencing this? I'm positive I merely did something stupid, so I apologize in advance.

**Comment by xolox** [comment]
**General thoughts about your issue:**

I'm not really sure what to make of this issue!

I would have expected the second `:verbose set foldexpr? foldmethod?` to show different values (confirming that the values are not correctly set from the ftplugin) but I also expected them to show where the conflicting settings were coming from (as in the first example), unfortunately (and strangely) that doesn't happen.

It seems like these are simply defaults that are not being overridden. However I can't seem to reproduce the issue given your steps to reproduce.

**Suggestions to find the root cause:**

1. One tangentially related thought / question: Do you have `ftplugin on` in your `~/.vimrc` script or not? In other words, do you have file type plugins enabled?

2. Another step that might help to narrow down the cause of this issue: Please run `setlocal` (without any arguments) in your note, once when the folding is working fine and once when the folding is broken, then copy/paste the output of both commands here (if there is no sensitive data in the settings).

 I suspect that this will show that not only the folding settings are missing the second time, but also all other settings customized by the plug-in, in other words the file type plug-in is simply not being activated at all.

3. This could have something to do with the fact that the second time you open the note, Vim most likely already has a matching hidden buffer that it re-uses. In case you want to investigate that line of thought, the `:buffers` command shows all your loaded buffers and the `:bwipeout` command can be used to *really* unload a buffer. If you do that and the next time you open the note everything is correct, then we are on to something :-).

**Comment by clessg** [comment]
Thanks for the response!

> One tangentially related thought / question: Do you have ftplugin on in your ~/.vimrc script or not? In other words, do you have file type plugins enabled?

I have the following. Is it what you're referring to?

`filetype plugin indent on`

> If you do that and the next time you open the note everything is correct, then we are on to something :-).

Ah yes, running `:bwipeout` and then opening the note again works! I'll make sure to run that when closing a note from now on.

Thanks again!
